### PR TITLE
Add py33 / py34 support

### LINKED ISSUE #3: Bring `protorpc` Python3 support.
...and Travis support.

See @craigcitro [comment][1].

/cc @tseaver 

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/654#issuecomment-76243464

### PR DESCRIPTION
**Pull request by tseaver**
I can squash this down, if you'd rather have it so.

Closes #3

### CODE REVIEW

**Comment by craigcitro** [comment]
@tseaver i'm not worried about squashing -- I like being able to see the mechanical changes broken up.

something confuses me, though: i don't see `six` being added as a dependency in `setup.py`, and it's not even in `tox.ini`. how is `tox` passing without it? are we picking it up transitively from one of our other deps?

**Comment by tseaver** [comment]
Good point -- I think `unittest2` requires it.  a134348 adds it explicitly to `setup.py`.

**Comment by craigcitro** [comment]
woooo! thanks!

**Comment by dhermes** [comment]
Wow!

**Pull request merged**
